# Generated by Django 5.2.8 on 2026-10-01 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='About Our School', max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='about/logo/')),
                ('cover_image', models.ImageField(blank=True, upload_to='about/cover/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
