"""
Django settings for CampusSecure project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_DIR = os.path.join(BASE_DIR, 'static')


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")

# one time url Sig token
TOKEN_SIGNING_KEY = config("TOKEN_SIGNING_KEY")



# ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=lambda value: value.split(","))
ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)



"""django Debug Toolbar ## debug-toolbar work with DEBUG=True """
import socket
hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
INTERNAL_IPS = [ip[:-1] + "1" for ip in ips] + ["127.0.0.1", "localhost", "192.168.110.127"]




FRONTEND_URL = str(config("FRONTEND_URL"))

# Application definition

INSTALLED_APPS = [
    "django_prometheus",

    # Django Admin
    "unfold",
    "unfold.contrib.filters", 

    # Default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# package as a app 
INSTALLED_APPS += [
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters", # for filtering
    "django_extensions",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "debug_toolbar",
]


# install app
INSTALLED_APPS += [
    "accounts",
    # "subscription",
    "documents",
    "exams",
    "audit",
    "school",
    "students",
    "payment",
]

MIDDLEWARE = [
    # External Middleware
    "django_prometheus.middleware.PrometheusBeforeMiddleware", # default prometheus do not ignore /metrics    
    "debug_toolbar.middleware.DebugToolbarMiddleware", # Django Query Debug 

    # default middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # External Middleware
    "utils.middleware.request_context.RequestContextMiddleware", # for logger 
    "utils.middleware.performance.RequestPerformanceMiddleware", # for performance logging
    "django_prometheus.middleware.PrometheusAfterMiddleware", # prometheus end

]

ROOT_URLCONF = 'CampusSecure.urls'

TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'CampusSecure.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# localhost postgres
# DATABASES = {
#     "default": {
#         # "ENGINE": "django.db.backends.postgresql",
#         "ENGINE": "django_prometheus.db.backends.postgresql",
#         "NAME": "django_db",
#         "USER": "django_user",
#         "PASSWORD": "django_passwd",
#         "HOST": "127.0.0.1",
#         "PORT": "7654",
#     }
    
# }

DATABASES = {
    "default": {
        # "ENGINE": "django.db.backends.postgresql",
        "ENGINE": "django_prometheus.db.backends.postgresql",
        "NAME": config("POSTGRES_DB"),
        "USER": config("POSTGRES_USER"),
        "PASSWORD": config("POSTGRES_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
    }
}






# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


"""---------> Config <-----------"""

# pillow heif register
import pillow_heif
pillow_heif.register_heif_opener()


STATIC_URL = '/static/' # aitar jonno template static file theke icon ba css file ber korte pare 
STATICFILES_DIRS = [STATIC_DIR]
# STATIC_ROOT = os.path.join(BASE_DIR, 'assets')
STATIC_ROOT = '/var/www/campus_secure/static/' # Static root


MEDIA_URL = "/media/"
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_ROOT = '/var/www/campus_secure/media/'

# PROTECTED_MEDIA_ROOT = os.path.join(BASE_DIR, 'protected_media')
PROTECTED_MEDIA_ROOT = '/var/www/campus_secure/protected_media/'

AUTH_USER_MODEL = "accounts.CustomUser"


# Django Unfold Admin Panel
from config.unfold_admin_panel import UNFOLD

# rest_framework settings or configurations
from config.drf_settings import REST_FRAMEWORK

# logger config with request context
from config.logger_config import LOGGING

# Cookie age config
from config.cookie_config import COOKIE_MAX_AGE

# Simple JWT token config
from config.jwt_config import SIMPLE_JWT

# spectacular configure
from config.spectacular_settings import SPECTACULAR_SETTINGS

"""CSRF Configure"""
from config.csrf_config import *

"""RabbitMQ Or Celery Configure"""
from config.celery_config import *



"""Email Configure"""
# email config
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")


"""Stripe Configure"""
from config.stripe_config import *
import stripe
stripe.api_key = STRIPE_SECRET_KEY



"""Django Prometheus"""
# PROMETHEUS_EXPORT_MIGRATIONS = True

"""Sentry Error Tracker"""
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration
sentry_sdk.init(
    dsn="https://408216e81290eb2b6231724361bf17f8@o4512100923015168.ingest.us.sentry.io/4512100933304320",
    send_default_pii=True,
    enable_logs=True,
    traces_sample_rate=1.0,
    profile_session_sample_rate=1.0,
    profile_lifecycle="trace",
    environment="production",
    integrations = [
        DjangoIntegration(),
        CeleryIntegration(),
    ]
)

SENTRY_CLIENT_SECRET = config("SENTRY_CLIENT_SECRET")

# swagger authentication config
import utils.swagger.authentication