# Generated by Django 5.2.8 on 2026-10-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='user_student_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='user_teacher_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='user_admin_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='user_staff_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='user_superuser_idx',
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='user_role_idx'),
        ),
    ]
