# Generated by Django 5.2.8 on 2026-09-10 13:53

import django.core.validators
import django.db.models.deletion
import django_prometheus.models
import exams.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(default=exams.models.current_year)),
                ('start_date', models.DateField(validators=[django.core.validators.MinValueValidator(exams.models.today_date)])),
                ('end_date', models.DateField(validators=[django.core.validators.MinValueValidator(exams.models.today_date)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ongoing', 'Ongoing'), ('finished', 'Finished'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ExamClass',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_classes', to='exams.exam')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_classes', to='school.studentclass')),
            ],
            options={
                'unique_together': {('exam', 'student_class')},
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_start', models.DateTimeField()),
                ('exam_end', models.DateTimeField()),
                ('full_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pass_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exam_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='exams.examclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='school.subject')),
            ],
            options={
                'unique_together': {('exam_class', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_absent', models.BooleanField(default=False)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='exams.examsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('exam_subject', 'student')},
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('StudentMark'), models.Model),
        ),
    ]
