# Generated by Django 5.2.8 on 2026-04-09 07:35

import django.db.models.deletion
import documents.helper
import utils.storages
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(choices=[('profile', 'Profile'), ('father_image', 'Father Image'), ('mother_image', 'Mother Image'), ('father_nid', 'Father NID'), ('mother_nid', 'Mother NID'), ('teacher_profile', 'Teacher Profile'), ('admin_profile', 'Admin Profile'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(storage=utils.storages.ProtectedFileSystemStorage(), upload_to=documents.helper.document_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_format', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('allowed_roles', models.JSONField(blank=True, null=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'file_type'), name='unique_owner_file_type')],
            },
        ),
    ]
